### ISSUE TITLE
zipped trees seem to have issues (under error_free_files/phylogenetic_trees)

### ISSUE THREAD

**Issue by smazrouee** [niemasd/FAVITES#12]
cat ./merged*
:0.0;
:0.0

path: .../error_free_files/phylogenetic_trees

## FAVITES Version

 Version 1.1.1  

## Environment

Mac

## Configuration File

{'vts_max_attempts': 100, 'SequenceEvolution': 'GTRGammaSeqGen', 'tree_rate_mean': -6.164, 'gemf_path': 'GEMF', 'rpg_p_in': 0.004, 'vts_model': 'logistic', 'hiv_i2_to_i3': 0, 'TreeUnit': 'LogNormal', 'seqgen_a_to_t': 0.691915, 'TransmissionTimeSample': 'HIVARTGranichGEMF', 'hmmemit_path': 'hmmemit', 'rpg_p_out': 0.0002, 'hiv_i3_to_d': 0, 'hiv_a2_to_i2': 0.48, 'hiv_s_to_i1_by_a3': 0, 'num_seeds': 50, 'seqgen_num_gamma_rate_categories': '', 'ContactNetwork': 'NetworkX', 'hiv_a1_to_a2': 4.33333, 'hiv_a1_to_d': 0, 'hiv_s_to_i1_seed': 0, 'hiv_a1_to_i1': 0.48, 'hiv_i1_to_i2': 8.666666666666666, 'hiv_i3_to_i4': 0, 'seqgen_freq_t': 0.232, 'hiv_a3_to_d': 0, 'hiv_s_to_i1_by_a1': 0.005625, 'Logging': 'File', 'seqgen_c_to_t': 10.282617, 'TreeNode': 'Simple', 'seqgen_path': 'seq-gen', 'seqgen_a_to_g': 9.587649, 'verbose': False, 'seqgen_gamma_shape': 0.405129, 'rpg_sizes': [10000, 10000, 10000, 10000, 10000], 'hiv_i4_to_d': 0, 'hiv_ns_to_d': 0, 'hiv_s_to_i1_by_i4': 0, 'hiv_a4_to_d': 0, 'hiv_s_to_i1_by_i3': 0, 'NumTimeSample': 'Once', 'ContactNetworkGenerator': 'RandomPartitionGraph', 'hiv_a2_to_d': 0, 'nw_rename_path': 'nw_rename', 'Sequencing': 'Perfect', 'end_time': 10, 'PostValidation': 'Dummy', 'out_dir': '/OUTPUT_DIR', 'TimeSample': 'GranichFirstART', 'hiv_a3_to_i3': 0, 'SeedSequence': 'VirusPureCoalescentGTRGamma', 'hiv_i1_to_d': 0, 'hiv_s_to_i1_by_a2': 0, 'viral_sequence_type': 'HIV1-B-DNA-POL-LITTLE', 'NodeAvailability': 'Bernoulli', 'NumBranchSample': 'Single', 'hiv_ns_to_s': 999999, 'hiv_s_to_i1_by_i1': 0.1125, 'NodeEvolution': 'VirusTreeSimulator', 'SourceSample': 'Random', 'seqgen_freq_c': 0.165, 'hiv_a2_to_a3': 0, 'hiv_s_to_i1_by_a4': 0, 'hiv_i3_to_a3': 0, 'java_path': 'java', 'vts_t50': -2, 'hiv_i4_to_a4': 0, 'seqgen_c_to_g': 0.863348, 'hiv_i1_to_a1': 0.5, 'Driver': 'Default', 'grinder_path': 'grinder', 'seqgen_freq_g': 0.212, 'hiv_a4_to_i4': 0, 'hiv_i2_to_d': 0, 'TransmissionNodeSample': 'GEMF', 'hiv_s_to_i1_by_i2': 0.0225, 'd_or_u': 'u', 'EndCriteria': 'GEMF', 'vts_growthRate': 2.851904, 'seed_population': 20, 'hiv_a3_to_a4': 0, 'hiv_s_to_d': 0, 'random_number_seed': '', 'hiv_i2_to_a2': 0.5, 'tree_rate_stdev': 0.3, 'seqgen_a_to_c': 1.765707, 'seqgen_g_to_t': 1.0, 'seqgen_freq_a': 0.392, 'SeedSelection': 'Random', 'node_sample_prob': 0.1, 'vts_n0': 1}

## Unexpected Behavior

content of merged phylogeny trees are copied above. Although every seed tree seems to be fine.  Below I copy one of them for instance: 

cat tree_9.*
-----------
(N96769|20612|1.166455:0):10.0;

(N96769|20612|1.166455:0.0):0.021674349495173547;

**Comment by niemasd** [comment]
Are you using `cat`? The files are gzipped, so you need to use `zcat` (or equivalently `gunzip -c` if you're on Mac and don't have `zcat`), not `cat`

**Comment by niemasd** [comment]
Never mind, I found the directory you're working in (`FAVITES/output/set7/output_7_1` within your home folder), and I see that the files are already unzipped. I'll investigate

**Comment by smazrouee** [comment]
First I unzipped them using gunzip on calab (OS/ver is actually: Linux
calab-fe 4.4.0-101-generic #124~14.04.1-Ubuntu SMP Fri Nov 10 19:05:36 UTC
2017 x86_64 x86_64 x86_64 GNU/Linux not Mac... typo).

**Comment by niemasd** [comment]
I was able to reproduce the error. It seems like an issue with merging the trees. I'll investigate and roll out an update to FAVITES when it's fixed

**Comment by niemasd** [comment]
Caught the issue: I forgot to update the merge function after gzipping the trees, so it was looking for files with extension `.tre` instead of `.tre.gz`. Fixing and will roll out in update later today

**Comment by niemasd** [comment]
Fixed in commit: https://github.com/niemasd/FAVITES/commit/12283fb71aa46759aad7798d63428bddeb16a48c

Building updated Docker image

**Comment by smazrouee** [comment]
Well, does this mean that I have to use the latest release instead? Cause
in that previous run I used 1.1.1 and plan to keep running all (over) 600
runs with the same version, to avoid other (probable) bugs or
inconsistencies. What is your suggestion? Thanks

**Comment by niemasd** [comment]
You can either switch to FAVITES version 1.1.3 (which now has the merging bug fixed), or you can use the method I described in my recent email to you to manually merge the trees. Switching versions will be easier, but it will take more compute time.

**Comment by niemasd** [comment]
Reproducing my "manually merge trees" solution here so I can close this ticket:

While I'm fixing the bug in merging trees, here's a way you can manually merge them instead of having to rerun. First, the relevant files:

* The seed tree can be found in `OUTPUT/seed_sequences/seed.txt`
* For each leaf in the seed tree, the corresponding sequence can be found in `OUTPUT/seed_sequences/seqgen.out`
* For each leaf sequence, the file `OUTPUT/seed_sequences/seed_sequences.tsv.gz` has the corresponding `N#` root of the individual trees
* The corresponding `N#` SeqGen files (which include the individual trees) can be found in `OUTPUT/SeqGen_output`

To do the merge, you should be able to do the following:

1. Load the seed tree (`OUTPUT/seed_sequences/seed.txt`)
2. Map each leaf in the seed tree to an `N#` label (seed tree -> sequence from `OUTPUT/seed_sequences/seqgen.out` -> `N#` label from `OUTPUT/seed_sequences/seed_sequences.tsv.gz`)
3. For each `N#` label, load the corresponding tree (`OUTPUT/SeqGen_output`) and set the corresponding leaf in the seed tree to the root of the `N#` tree
