### ISSUE TITLE
example config file now working

### ISSUE THREAD

**Issue by smirarab** [niemasd/FAVITES#18]
Starting from FAVITES's own example config file: https://github.com/niemasd/FAVITES/blob/master/example/example_config.json

on a fresh docker install I get:

~~~bash
run_favites_docker.py -c example_config.json
Traceback (most recent call last):
  File "/FAVITES/run_favites.py", line 72, in <module>
    parseArgs()
  File "/FAVITES/run_favites.py", line 64, in parseArgs
    MF.read_config(config, config['verbose'])
  File "/FAVITES/modules/FAVITES_ModuleFactory.py", line 39, in read_config
    assert req in config, "Parameter %r of %s_%s module is not in the configuration file!" % (req, module, config[module])
AssertionError: Parameter 'vts_max_attempts' of NodeEvolution_VirusTreeSimulator module is not in the configuration file!
~~~

## FAVITES Version
1.1.5

## Environment
Docker on MAC

## Configuration File
https://github.com/niemasd/FAVITES/blob/master/example/example_config.json

## Unexpected Behavior
see above

**Comment by niemasd** [comment]
Thanks for catching this. I forgot to update the example directory after the recent updates. It's fixed here: https://github.com/niemasd/FAVITES/commit/52abe544b19ccad9793b75d8a2ca76876d85efb5
