### ISSUE TITLE
Singularity Compatible Version of Favites Issue

### ISSUE THREAD

**Issue by sinamlk** [niemasd/FAVITES#24]
I was trying to run singularity version of Favites.
I ran Favites on my Comet account on login and computing node. In both cases, I got the error message " ERROR: Configuration disallows users from running directory based containers
ABORT  : Retval = 255".
I ran it in my home directory on Comet and simply using the following command:
python3 run_favites_singularity.py -c example_config.json -u 1.1.10

**Comment by niemasd** [comment]
I am able to reproduce the error in my Comet environment. I will investigate

**Comment by niemasd** [comment]
Problem fixed in newest version of [run_favites_singularity.py](https://github.com/niemasd/FAVITES/blob/master/run_favites_singularity.py)
