### ISSUE TITLE
Breaks when using "-u" in command line and not specifying the version

### ISSUE THREAD

**Issue by pekarj** [niemasd/FAVITES#29]
## FAVITES Version

The issue is using "-u" without the version specified. When using "-u 1.1.35", it works. 

## Environment

OS 10.14, using Docker

## Unexpected Behavior

When using "-u"  in the command line input without the version specified, I get the following output. When using "-u 1.1.35", the program works correctly.

$ python3 run_favites_docker.py -c example/example_configNEW.json
ERROR: Output directory exists. Overwrite? All contents will be deleted. (y/n) y
Traceback (most recent call last):
  File "/FAVITES/run_favites.py", line 72, in <module>
    parseArgs()
  File "/FAVITES/run_favites.py", line 64, in parseArgs
    MF.read_config(config, config['verbose'])
  File "/FAVITES/modules/FAVITES_ModuleFactory.py", line 39, in read_config
    assert req in config, "Parameter %r of %s_%s module is not in the configuration file!" % (req, module, config[module])
AssertionError: Parameter 'gemf_path' of EndCriteria_GEMF module is not in the configuration file!

**Comment by niemasd** [comment]
The example usage you specified does not have `-u`; are you sure you specified it? This is what's in your post (and only `-c` is specified, not `-u`):

> $ python3 run_favites_docker.py **-c** example/example_configNEW.json

I can't run Docker on any of the computers I have access to at the moment, but I played with the [run_favites_docker.py](https://github.com/niemasd/FAVITES/blob/master/run_favites_docker.py) script just to see what would happen up to the point of actually running Docker. When I specify `-u` vs. when I specify `-u 1.1.35`, when I put a print statement after [line 110](https://github.com/niemasd/FAVITES/blob/d76f4ca4340ff79775e9bb9ee866d2146c1b5f5a/run_favites_docker.py#L110) to just print the `tag` and `version` variables, in both cases, I get exactly `1.1.35` and `niemasd/favites:1.1.35`, respectively. All subsequent commands use `tag` and `version` (which seem t correctly be identical in both `-u` and `-u 1.1.35`), so it seems as though the results should be identical

When `-u` failed and `-u 1.1.35` worked, did you have a functional internet connection?

**Comment by pekarj** [comment]
Sorry -- I copied and pasted the wrong thing. 

I'm now using the most up-to-date version of the script, and -u and -u 1.1.35 both work. Mihir was probably using an older version of that script. Looks like there is no issue then. Thank you!
