### ISSUE TITLE
"KeyError: 'None'", for my Transmission Network File

### ISSUE THREAD

**Issue by pekarj** [niemasd/FAVITES#30]
## FAVITES Version

FAVITES version 1.1.35

## Environment

macOS Catalina 10.15, and using Docker

## Configuration File

Config file:
[FAVITES_config.json.txt](https://github.com/niemasd/FAVITES/files/3753969/FAVITES_config.json.txt)

The transmission network and contact network files:
[transmission_network_file.txt](https://github.com/niemasd/FAVITES/files/3754053/transmission_network_file.txt)
[contact_network_file.txt](https://github.com/niemasd/FAVITES/files/3754054/contact_network_file.txt)

## Unexpected Behavior

Loaded my own Transmission Network and Contact Network Files. FAVITES seemed unable to correctly parse "None" from the Transmission Network file when reading seed infections. 

Error message:

========================   Simulation Process  ========================
Loading contact network... done
Creating ContactNetwork object... done
Selecting seed nodes... done
Infecting seed nodes... done
Performing transmission simulations...Traceback (most recent call last):
  File "/FAVITES/run_favites.py", line 75, in <module>
    MF.modules['Driver'].run('/'.join(expanduser(abspath(argv[0])).split('/')[:-1]), ORIG_CONFIG)
  File "/FAVITES/modules/Driver_Default.py", line 164, in run
    u,v = MF.modules['TransmissionNodeSample'].sample_nodes(t)
  File "/FAVITES/modules/TransmissionNodeSample_TransmissionFile.py", line 26, in sample_nodes
    return GC.contact_network.get_node(u), GC.contact_network.get_node(v)
  File "/FAVITES/modules/ContactNetwork_NetworkX.py", line 134, in get_node
    return Node(self, name, self.name_to_num[name])
KeyError: 'None'

**Comment by niemasd** [comment]
I see the issue: my transmission network file stuff isn't properly handling late seeds (i.e., it assumes all seeds are before the first transmission event). I'll try to fix it soon

**Comment by niemasd** [comment]
Fixed in 1.1.36
