### ISSUE TITLE
Running config_designer.py causes my computer account logging out

### ISSUE THREAD

**Issue by yueyujiang** [niemasd/FAVITES#31]
## FAVITES Version
FAVITES 1.1.35

## Environment
macOS Mojave Version 10.14.6, running config_designer.py via python 3.7.4

## Unexpected Behavior
Running config_designer.py will cause my computer account logging out.

**Comment by niemasd** [comment]
It seems like this is a bug introduced in a recent Mac OS X update that makes new versions of Python be incompatible with Tkinter (a Python GUI package). This post seems to suggest that downgrading to Python 3.7.0 may be a temporary fix:

https://github.com/ContinuumIO/anaconda-issues/issues/11165#issuecomment-531278111

**Comment by yueyujiang** [comment]
It works! Thank you.

> It seems like this is a bug introduced in a recent Mac OS X update that makes new versions of Python be incompatible with Tkinter (a Python GUI package). This post seems to suggest that downgrading to Python 3.7.0 may be a temporary fix:
> 
> [ContinuumIO/anaconda-issues#11165 (comment)](https://github.com/ContinuumIO/anaconda-issues/issues/11165#issuecomment-531278111)

It works! Thank you.

**Comment by niemasd** [comment]
Glad you got it working!
