### ISSUE TITLE
No such file or directory: 'ID_xxx_simple.nex'

### ISSUE THREAD

**Issue by yueyujiang** [niemasd/FAVITES#32]
## FAVITES Version
FAVITES 1.1.35

## Environment
macOS Mojave Version 10.14.6, Docker

## Configuration File
[0.json.txt](https://github.com/niemasd/FAVITES/files/3785202/0.json.txt)

## Unexpected Behavior
Running the FAVITES via run_favites_docker.py, the following error occurs sometimes.

=============================================================
Evolving trees and sequences to end time...Traceback (most recent call last):
  File "/FAVITES/modules/NodeEvolution_VirusTreeSimulator.py", line 124, in evolve_to_current_time
    parts = open('ID_%s_simple.nex'%str(seed)).read().strip().split('Translate')[1].split('tree TREE1')
FileNotFoundError: [Errno 2] No such file or directory: 'ID_4958_simple.nex'

**Comment by niemasd** [comment]
Did this get resolved? If so, what was the fix?

**Comment by yueyujiang** [comment]
Hi Niema,

No, it hasn't been solved. I just change to other configurations. Sorry
about closing the issue if I shouldn't do that.

Thanks,
Yueyu
