### ISSUE TITLE
Issue with label_internal_nodes helper script

### ISSUE THREAD

**Issue by pekarj** [niemasd/FAVITES#35]
## FAVITES Version

Not necessary. 

## Environment

Not necessary.

## Configuration File

No config file needed. I've included an example tree, transmission network, and resulting tree after running the script instead.

[transmission_network.txt](https://github.com/niemasd/FAVITES/files/5081919/transmission_network.txt)
[tree_217.time.tre.zip](https://github.com/niemasd/FAVITES/files/5081921/tree_217.time.tre.zip)
[tree_217.time.labelInternal.tree.zip](https://github.com/niemasd/FAVITES/files/5081922/tree_217.time.labelInternal.tree.zip)

## Unexpected Behavior

I was working on some stuff where I had to label internal nodes, and had been using your helper script from FAVITES, but I noticed I was getting some funky labels, where sometimes an internal node would be labeled by someone who wasn't yet infected. There isn't an error message for this. 

I think the issue is where you read in the transmission network. You use the following code: 

```
# read seeds and infection times from transmission network
tn = open(tn_path)
inf = {None:float('inf')}; seeds = set()
for l in tn:
    if isinstance(l,bytes):
        u,v,t = l.decode().strip().split('\t')
    else:
        u,v,t = l.strip().split('\t')
    if u == 'None':
        seeds.add(v); inf[v] = float('-inf')
    else:
        inf[v] = float(t)
```

However, in the final line, if you've already read in a node when it was infected, but then the node recovered or was removed from the network, you would rewrite the infection time as this recovery/leaving time. If I add the following if statement to the last line, I find the issue to be resolved. 

```
if v not in inf.keys(): 
    inf[v] = float(t)
```
I could be misunderstanding though?

**Comment by niemasd** [comment]
Woops, thanks for catching that! I wrote that not thinking about how I implemented recovery into FAVITES. Thanks for the fix! I've incorporated it now

https://github.com/niemasd/FAVITES/commit/7215cf24c9c7a7d6804c3edc01a45f001f833e23
