### ISSUE TITLE
run_favites_docker.py only works on Linux with sudo

### ISSUE THREAD

**Issue by ghart-IDM** [niemasd/FAVITES#40]
I am trying to get FAVITES up and running to see if will satsify our needs (with potentially adding our only implementations). I have followed the Docker installation instructions. When I try running `run_favites_docker.py --config config.json` or `run_favites_docker.py -u --config config.json` I get the following error:

> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json: dial unix /var/run/docker.sock: connect: permission denied
> Traceback (most recent call last):
>   File "/usr/local/bin/run_favites_docker.py", line 105, in <module>
>     o = check_output(['docker','images']).decode().splitlines()
>   File "/home/ghart/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/home/ghart/anaconda3/lib/python3.8/subprocess.py", line 512, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['docker', 'images']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/run_favites_docker.py", line 110, in <module>
>     raise RuntimeError("docker images command failed\n%s"%e.output)
> RuntimeError: docker images command failed
> b''
> 

I can successfully run with `sudo run_favites_docker.py --config config.json` but then the output files (and directory) are owned by root and cannot be touched by a regular user (or other programs) it would be great if there was an easy fix for this. I am try installing manually if there is not.

## FAVITES Version

1.2.7

## Environment

Operating System: Ubuntu 20.04.1 LTS
Kernel: Linux 5.4.0-73-generic
Architecture: x86-64

## Configuration File

This is the example file given in the wiki (which I am using just to get things running):

> {
>     # Module Implementations
>     "Driver": "Default",
>     "Logging": "STDOUT",
>     "TreeNode": "Simple",
>     "ContactNetwork": "NetworkX",
>     "ContactNetworkGenerator": "Complete",
>     "SeedSelection": "Random",
>     "SeedSequence": "Random",
>     "EndCriteria": "Transmissions",
>     "TransmissionTimeSample": "Fixed",
>     "TransmissionNodeSample": "RandomSingleInfection",
>     "NodeEvolution": "VirusTreeSimulator",
>     "SequenceEvolution": "NoMutation",
>     "SourceSample": "Random",
>     "NumTimeSample": "Once",
>     "TimeSample": "End",
>     "NumBranchSample": "Single",
>     "TreeUnit": "LogNormal",
>     "NodeAvailability": "Perfect",
>     "Sequencing": "Perfect",
> 
>     # Parameter Choices
>     "end_transmissions": 5,
>     "fixed_transmission_time_delta": 0.5,
>     "java_path": "java",
>     "num_cn_nodes": 100,
>     "num_seeds": 1,
>     "out_dir": "FAVITES_output",
>     "seed_sequence_length": 20,
>     "tree_rate_mean": -6.164,
>     "tree_rate_stdev": 0.3,
>     "vts_growthRate": 2.851904,
>     "vts_max_attempts": 10,
>     "vts_model": "logistic",
>     "vts_n0": 1,
>     "vts_t50": -2
> }

## Unexpected Behavior

See above

**Comment by niemasd** [comment]
Thanks for reaching out! Are you able to use Docker commands from your normal account? For example, are you able to do the following?

```bash
docker images
```

You may need to do something like the following to be able to manage Docker from a non-root user:

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by ghart-IDM** [comment]
You are right. It was a local issues with the docker instill. I have fixed it and it is working now. Thank you.

**Comment by niemasd** [comment]
No problem, glad to hear it!
