### ISSUE TITLE
config_designer.py fails to write JSON

### ISSUE THREAD

**Issue by ArtPoon** [niemasd/FAVITES#42]
Running `config_designer.py` to try generating a JSON with configuration from [Miller et al.](https://academic.oup.com/emph/article/10/1/305/6648346) paper supplement.  Interface failed to launch file dialog.  It seems to me that this script is importing a function from `tkinter.filedialog` but not the `filedialog` submodule itself:
```python
art@Wernstrom FAVITES % grep -n filedialog config_designer.py
6:from tkinter.filedialog import asksaveasfile
135:    f = filedialog.asksaveasfile(mode='w', defaultextension=".json")
```
so when this submodule is called on line 135 then Python throws an exception (see above).
I think line 135 should be:
```python
    f = asksaveasfile(mode='w', defaultextension=".json")
```

## FAVITES Version

df946c81137ff41ac690d41828d5c1f5138a22c1

## Environment

macOS 12.5.1, manually installed FAVITES from git clone

## Configuration File

Not applicable, I was running the `config_designer.py` interface to generate a config file.

## Unexpected Behavior

```console
art@Wernstrom FAVITES % python3 config_designer.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/art/git/FAVITES/config_designer.py", line 135, in save_file
    f = filedialog.asksaveasfile(mode='w', defaultextension=".json")
NameError: name 'filedialog' is not defined
```

**Comment by ArtPoon** [comment]
I confirmed that the following change fixed this problem:
```diff
diff --git a/config_designer.py b/config_designer.py
index aba3cbc..f75d756 100755
--- a/config_designer.py
+++ b/config_designer.py
@@ -132,11 +132,11 @@ def format_output():
     out_lines.append('}')
     return '\n'.join(out_lines)
 def save_file():
-    f = filedialog.asksaveasfile(mode='w', defaultextension=".json")
+    f = asksaveasfile(mode='w', defaultextension=".json")
     if f is None:
         return
     f.write(format_output())
     f.close()
```

**Comment by niemasd** [comment]
Ah, thanks for catching that! Yes, it should be `asksaveasfile` (rather than `filedialog.asksaveasfile`). It was working on my system, likely because of the call to `from tkinter import *` (which I assume resulted in the importing of `filedialog` from `tkinter`), but my intention was to use `asksaveasfile` directly.

Fixed in https://github.com/niemasd/FAVITES/commit/bd85bffa986fa06eff18176d4588db37d2ab5739. Thanks again!
