### ISSUE TITLE
ERROR?

### ISSUE THREAD

**Issue by liamxg** [niemasd/FAVITES#43]
bash simulation_pipeline.sh ../../Data/Gleamviz/seedings.tsv ../../Data/Gleamviz/metadata_cities.tsv ../../FAVITES/run_favites_docker.py ../../Data/FAVITES/flu_spread_config.json simulation_output
Traceback (most recent call last):
  File "/Users/lixingguang/Downloads/0_ggplot2/hzi-bifo/Phylogeography_Paper/Software/Simulation/../../FAVITES/run_favites_docker.py", line 105, in <module>
    o = check_output(['docker','images']).decode().splitlines()
  File "/Users/lixingguang/opt/miniconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/lixingguang/opt/miniconda3/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/lixingguang/opt/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/lixingguang/opt/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
gunzip: can't stat: FAVITES_output/error_free_files/sequence_data.fasta.gz (FAVITES_output/error_free_files/sequence_data.fasta.gz.gz): No such file or directory
gunzip: can't stat: FAVITES_output/error_free_files/transmission_network.txt.gz (FAVITES_output/error_free_files/transmission_network.txt.gz.gz): No such file or directory
gunzip: can't stat: FAVITES_output/error_free_files/phylogenetic_trees/tree_0.tre.gz (FAVITES_output/error_free_files/phylogenetic_trees/tree_0.tre.gz.gz): No such file or directory
gunzip: can't stat: FAVITES_output/error_free_files/phylogenetic_trees/tree_0.time.tre.gz (FAVITES_output/error_free_files/phylogenetic_trees/tree_0.time.tre.gz.gz): No such file or directory
gunzip: can't stat: FAVITES_output/seed_sequences.tsv.gz (FAVITES_output/seed_sequences.tsv.gz.gz): No such file or directory
Error in file(file, "r") : cannot open the connection
Calls: read.tree -> scan -> file
In addition: Warning message:
In file(file, "r") :
  cannot open file 'FAVITES_output/error_free_files/phylogenetic_trees/tree_0.tre': No such file or directory
Execution halted
cp: FAVITES_output/error_free_files/sequence_data.fasta: No such file or directory
head: FAVITES_output/seed_sequences.tsv: No such file or directory
head: FAVITES_output/seed_sequences.tsv: No such file or directory

**Comment by niemasd** [comment]
Thanks for reaching out! Based on the first line of what you wrote:

```
bash simulation_pipeline.sh ...
```

It seems like you're using someone else's pipeline (`simulation_pipeline.sh`) that happens to utilize FAVITES within it. The specific FAVITES-related error you're getting is the following part of your output that you shared:

```
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

which means that you're trying to run the Docker version of FAVITES (via `run_favites_docker.py`, as per the beginning of the output you shared), but you don't have Docker installed on your machine

To fix *this specific* issue, you will need to install Docker on your machine:

https://github.com/niemasd/FAVITES/wiki/Installation#using-docker-recommended

After installing Docker, the `run_favites_docker.py` script should be able to run. However, I cannot provide support for the rest of the pipeline you're trying to run (`simulation_pipeline.sh`), as I did not develop it, so you will need to reach out to the original developers of that script for further support

**Comment by liamxg** [comment]
did you see this? https://github.com/hzi-bifo/Phylogeography_Paper/tree/master/Software/Simulation
