### ISSUE TITLE
Error on running run_favites.py 

### ISSUE THREAD

**Issue by MarriaK** [niemasd/FAVITES#44]
Hello,

I hope you're doing well. I've been attempting to execute the FAVITES model in a loop with my configuration files, aiming to generate 100 samples for each configuration on a MacBook Pro M1. However, I'm encountering an issue. When I execute `run_favites.py` in a loop, I encounter the following error:

```
GC.virus_history[virus.get_label()].append((time,self))
KeyError: 'N1'
```

Additionally, I attempted to use `run_favites_docker.py`, but ran into a connection issue with Docker.

Could you provide assistance or guidance on resolving these issues to successfully run your code? Your help would be greatly appreciated.

## Configuration File

{'ContactNetwork': 'NetworkX', 
'ContactNetworkGenerator': 'BarabasiAlbert', 
'Driver': 'Default', 
'EndCriteria': 'GEMF', 
'Logging': 'STDOUT', 
'NodeAvailability': 'Perfect', 
'NodeEvolution': 'VirusTreeSimulator',
 'NumBranchSample': 'Fixed', 
 'NumTimeSample': 'Once', 
 'SeedSelection': 'EdgeWeighted', 
 'SeedSequence': 'User', 
 'SequenceEvolution': 'GTRGammaSeqGen', 
 'Sequencing': 'Perfect',
  'SourceSample': 'Random',
   'TimeSample': 'End', 
   'TransmissionNodeSample': 'GEMF',
    'TransmissionTimeSample': 'SIGEMF',
     'TreeNode': 'Simple', 
     'TreeUnit': 'ConstantRate', 
     'end_time': 200, 
     'gemf_path': 'GEMF',
      'hmmemit_path': 'hmmemit', 
      'java_path': 'java', 
      'num_cn_nodes': 100,
       'num_edges_from_new': 1, 
       'num_seeds': 1, 
       'num_viruses_per_cn_sample': 10, 
       'out_dir': '/FAVITES_MOUNT/OUTPUT_DIR',
        'seed_seqs': ['CACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAACACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAACACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAACACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAACACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAACACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAACACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAACACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAACACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAACACCTACAGCTGCCCTAGTGGTGTCGCAGTTACTCCGGATCCCACAAGCTGTCGTGGACATGGTAGCGGGGGCCCACTGGGGAGTCCTGGCGGGCCTTGCATACTATTCCATGGTGGGGAACTGGGCTAAGGTTTTGATTGTGATGCTGCTCTTTGCCGGCGTCGACGGGGAGACCCACACGACGGGGGGGTCGGCGGCCAAGAGTACTTTCAGGCTTACGAACATCTTTTCGCTAGGGCCGGCTCAGAAAATCCAGCTTATAA'],
         'seir_beta_by_i': 0.01, 
         'seir_beta_seed': 0, 
         'seir_delta': 0.93, 
         'seir_lambda': 0.06,
          'infection_rate': 0.05, 
          'si_beta_seed': 0,
           'si_beta_by_i': 0.01, 
           'seqgen_a_to_c': 6.461945, 
           'seqgen_a_to_g': 16.399738, 
           'seqgen_a_to_t': 3.197035, 
           'seqgen_c_to_g': 0.750543, 
           'seqgen_c_to_t': 14.629816, 
           'seqgen_g_to_t': 1.0, 
           'seqgen_freq_a': 0.178159, 
           'seqgen_freq_c': 0.263322, 
           'seqgen_freq_g': 0.233821, 
           'seqgen_freq_t': 0.324698, 
           'seqgen_gamma_shape': 0.1, 
           'seqgen_num_gamma_rate_categories': '',
            'seqgen_path': 'seq-gen', 
            'tree_mutation_rate': 0.01,
             'ts_truncnorm_loc': 0.9,
              'ts_truncnorm_scale': 5, 
              'vts_growthRate': 0.05, 
              'vts_max_attempts': 10000,
               'vts_model': 'exponential', 
               'vts_n0': 1,
                'vts_t50': -5.5, 
               'random_number_seed': '', 
               'verbose': False}
## Unexpected Behavior

SOPHIConfig/exponential_SI_config_01.json
/Users/maryamkafi/Documents/PhD_Project/FAVITES-master/run_favites.py:50: UserWarning: Output directory specified in command line (FAVITES_output_expSI_contemp_T5_N5_E1_101) and config file (/FAVITES_MOUNT/OUTPUT_DIR). Command line will take precedence
  warn("Output directory specified in command line (%s) and config file (%s). Command line will take precedence" % (args.out_dir, config['out_dir']))
ERROR: Output directory exists. Overwrite? All contents will be deleted. (y/n) y
/---------------------------------------------------------------------\
| FAVITES - FrAmework for VIral Transmission and Evolution Simulation |
|                           Version 1.2.11                            |
|                         Niema Moshiri 2017                          |
\---------------------------------------------------------------------/

========================   Simulation Process  ========================
Loading contact network... done
Creating ContactNetwork object... done
Selecting seed nodes... done
Infecting seed nodes...Traceback (most recent call last):
  File "/Users/maryamkafi/Documents/PhD_Project/FAVITES-master/run_favites.py", line 79, in <module>
    MF.modules['Driver'].run('/'.join(expanduser(abspath(argv[0])).split('/')[:-1]), ORIG_CONFIG)    
  File "/Users/maryamkafi/Documents/PhD_Project/FAVITES-master/./modules/Driver_Default.py", line 146, in run
    node.infect(0.0,virus)
  File "/Users/maryamkafi/Documents/PhD_Project/FAVITES-master/./modules/ContactNetworkNode_NetworkX.py", line 117, in infect
    GC.virus_history[virus.get_label()].append((time,self))
KeyError: 'N1'
/Users/maryamkafi/Documents/PhD_Project/FAVITES-master/run_favites.py:50: UserWarning: Output directory specified in command line (FAVITES_output_expSI_contemp_T5_N5_E1_101) and config file (/FAVITES_MOUNT/OUTPUT_DIR). Command line will take precedence
  warn("Output directory specified in command line (%s) and config file (%s). Command line will take precedence" % (args.out_dir, config['out_dir']))

**Comment by niemasd** [comment]
Thanks for reaching out! I'm planning to deprecate the original FAVITES at some point soon, and I generally recommend that people switch over to the newer (and much faster, but slightly less flexible) FAVITES-Lite:

https://github.com/niemasd/FAVITES-Lite

Looking at your CONFIG file, it looks like the simulations you're trying to run *should* work in FAVITES-Lite as well (i.e., I don't think you're using any models that exist in FAVITES but not in FAVITES-Lite). You can use the FAVITES-Lite Config Designer web application to design a CONFIG file for FAVITES-Lite:

https://niema.net/FAVITES-Lite

**Comment by niemasd** [comment]
I went through the FAVITES-Lite Config Designer and designed an equivalent FAVITES-Lite config file based on the one you provided. I was able to *almost* match everything, with just the following exception:

* In your FAVITES config file, for simulating a coalescent phylogeny along the transmission network, you're using the "exponential effective population size growth" model, but FAVITES-Lite doesn't currently support this model
    * I recommend using constant effective population size instead, which shouldn't impact the resulting tree *too* much (the transmission network is the biggest impact on phylogeny shape + branch lengths)
    * I chose 1 as the effective intra-host viral population size, as again, I don't think it'll impact your results significantly, but you may want to tweak this value and choose something that works for you
* In FAVITES-Lite, we require a "Viral Phylogeny (Seeds)" model, which merges the viral phylogenies you get from each seed individual into a single tree
    * Your simulations seem to only have 1 seed individual, so the choice of this model shouldn't do anything (since there's only 1 seed, so nothing to merge)
    * I arbitrarily selected "Coalescent (Neutral)" with a parameter of 1 because it shouldn't matter
    * I don't think I've tested FAVITES-Lite with just a single seed, so if this crashes, let me know and I can fix it
* In FAVITES-Lite, I haven't added the ability to provide a seed sequence: just to randomly generate one. However, when I BLASTed your Seed Sequence, I see it's a real viral sequence, so I imagine you care about the sequence
    * For now, I've set it to randomly generate a sequence of length 2640 (the length of your sequence) with the base frequencies you provided in your original config file
    * I'll try to add the ability to use a user-provided sequence soon, but not sure when (swamped with teaching these next few weeks)

Here's the resulting FAVITES-Lite config file, which you can open in the FAVITES-Lite Config Designer to play around with:

[config.json](https://github.com/niemasd/FAVITES/files/14542941/config.json)

**Comment by MarriaK** [comment]
Thank you so much for your help. I used the config file that you provided, and it ran successfully except for Viral Phylogeny (Seeds) and issue is:

```
[2024-03-08 18:38:14] === Viral Phylogeny (Seeds) ===
[2024-03-08 18:38:14] Model: Coalescent (Neutral)
[2024-03-08 18:38:14] Parameter: height: 1
Traceback (most recent call last):
  File "/Users/maryamkafi/Documents/PhD_Project/FAVITES-Lite/favites_lite.py", line 110, in <module>
    PLUGIN_FUNCTIONS[step][model](params, out_fn, config, GLOBAL, verbose=verbose)
  File "/Users/maryamkafi/Documents/PhD_Project/FAVITES-Lite/plugins/viral_phylogeny_seeds/common_treesap.py", line 40, in treesap_coalescent_const_pop
    treesap_seed("Coalescent (Neutral)", params, out_fn, config, GLOBAL, verbose=verbose)
  File "/Users/maryamkafi/Documents/PhD_Project/FAVITES-Lite/plugins/viral_phylogeny_seeds/common_treesap.py", line 18, in treesap_seed
    tree = coalescent_const_pop_tree(100., len(chain_trees), continuous=True)
  File "/Users/maryamkafi/.local/lib/python3.10/site-packages/treesap/coalescent.py", line 27, in coalescent_const_pop_tree
    raise ValueError("num_leaves must be at least 2")
ValueError: num_leaves must be at least 2
```

Another question I have is regarding the Favites model. Do you know why I encounter an error when running it within a for loop? Also, is there a possibility to execute the Favites model successfully in a loop? Could this issue be related to the fact that I'm using a Mac instead of Linux?

**Comment by niemasd** [comment]
Thanks for following up! If you don't mind, can we continue this conversation in a GitHub Issue in the FAVITES-Lite repo?

https://github.com/niemasd/FAVITES-Lite/issues/15

Feel free to reopen this GitHub Issue if you prefer keeping things here, but I think continuing with FAVITES-Lite is the best solution (I just need to patch this bug)
